services:
  nginx-server:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/server/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend:/var/www/src
  nginx-client:
    image: "nginx:stable-alpine"
    ports:
      - "8001:80"
    volumes:
      - ./nginx/client/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/var/www/src

  php:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
       - ./backend:/var/www/src
       - ./backend/uploads:/var/www/src/uploads
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "album_db"
      MYSQL_USER: "album"
      MYSQL_PASSWORD: "pass"
      MYSQL_ROOT_PASSWORD: "pass"
    ports:
      - "33064:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: